MINECRAFT:ARMOR_STAND: material:AIR:15
CREEPER: material:OAK_LEAVES:15
ENDER_CRYSTAL: material:GLASS:15
ENDER_DRAGON: material:CRYING_OBSIDIAN:15
ENDERMAN: material:BLACK_SHULKER_BOX:15
SKELETON: material:WHITE_SHULKER_BOX:15
SLIME: material:SLIME_BLOCK:15
STRAY: material:WHITE_SHULKER_BOX:15
ZOMBIE: material:GREEN_SHULKER_BOX:15
ZOMBIE_VILLAGER: material:GREEN_SHULKER_BOX:15