MINECRAFT:ARMOR_STAND: AIR
CREEPER: OAK_LEAVES
ENDER_CRYSTAL: GLASS
ENDER_DRAGON: CRYING_OBSIDIAN
ENDERMAN: BLACK_SHULKER_BOX
SKELETON: WHITE_SHULKER_BOX
SLIME: SLIME_BLOCK
STRAY: WHITE_SHULKER_BOX
ZOMBIE: GREEN_SHULKER_BOX
ZOMBIE_VILLAGER: GREEN_SHULKER_BOX